---
- name: Deploy rosbagBrowser
  hosts: all
  environment:
    DJANGO_SETTINGS_MODULE: "rosbagBrowser.settings_{{ django_config }}"
  tasks:
    - name: Checkout code
      synchronize:
        src: "{{ item }}"
        dest: ~/rosbagBrowser/
        delete: true
      with_items:
        - ../landingpage
        - ../rosbagBrowser
        - ../rosbagsApp
        - ../LICENSE
        - ../manage.py
        - ../README.md
        - ../requirements.txt
    - name: Deploy secrets
      template:
        src: .env.j2
        dest: ~/rosbagBrowser/.env
    - name: Install dependencies
      become: true
      apt:
        name:
          - python3-virtualenv
          - nginx
        update_cache: true
        state: latest

    - name: Install python deps to venv
      pip:
        virtualenv: ~/rosbagBrowser/.venv-deployment
        requirements: ~/rosbagBrowser/requirements.txt

    # Gunicorn systemd
    - name: Deploy gunicorn systemd socket
      become: true
      copy:
        src: gunicorn.socket
        dest: /etc/systemd/system/
    - name: Deploy gunicorn systemd service
      become: true
      template:
        src: gunicorn.service.j2
        dest: /etc/systemd/system/gunicorn.service

    # Nginx config
    - name: Deploy nginx config
      become: true
      template:
        src: nginx_config.j2
        dest: /etc/nginx/sites-available/rosbagBrowser
    - name: Enable rosbagBrowser site for nginx
      become: true
      file:
        path: /etc/nginx/sites-enabled/rosbagBrowser
        src: /etc/nginx/sites-available/rosbagBrowser
        state: link
    - name: Ensure default nginx site is not enabled
      become: true
      file:
        path: /etc/nginx/sites-enabled/default
        state: absent
    - name: Test nginx config
      become: true
      command: nginx -t
    - name: Enable/Start nginx service
      become: true
      systemd:
        name: nginx
        state: restarted
        enabled: true

    # Django setup
    - name: Run django deployment checks
      shell:
        chdir: ~/rosbagBrowser
        cmd: |
          set -e
          . .venv-deployment/bin/activate
          python3 manage.py check --deploy --fail-level WARNING
    - name: run django migrations
      shell:
        chdir: ~/rosbagBrowser
        cmd: |
          set -e
          . .venv-deployment/bin/activate
          python3 manage.py migrate
    - name: Create static files directory
      become: true
      file:
        path: "/django_static/static"
        state: directory
        owner: "{{ ansible_user }}"
        mode: u=rwx,g=rx,o=rx
    - name: Dry run collecting static files
      shell:
        chdir: ~/rosbagBrowser
        cmd: |
          set -e
          . .venv-deployment/bin/activate
          python3 manage.py collectstatic --noinput --clear --dry-run
    - name: Collect static files
      shell:
        chdir: ~/rosbagBrowser
        cmd: |
          set -e
          . .venv-deployment/bin/activate
          python3 manage.py collectstatic --noinput --clear

    # (Re)start gunicorn
    - name: Start gunicorn
      become: true
      systemd:
        name: gunicorn
        state: restarted
        enabled: true
        daemon_reload: true
