name: Deploy to Production
on:
  push:
    branches:
      - main

jobs:
  deploy_ansible:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Add SSH key
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
        run: |
          mkdir -p /home/runner/.ssh
          ssh-keyscan rosbag.spatz.wtf >> /home/runner/.ssh/known_hosts
          echo "${{ secrets.PRODUCTION_SSH_KEY }}" > /home/runner/.ssh/github_actions
          chmod 600 /home/runner/.ssh/github_actions
          ssh-agent -a $SSH_AUTH_SOCK > /dev/null
          ssh-add /home/runner/.ssh/github_actions
      - name: Run ansible
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
        run: |
          ansible-playbook \
           -i deployment/production_inventory.ini \
           --extra-vars \
            "gitlab_key=${{ secrets.PRODUCTION_GITLAB_KEY }} \
             gitlab_secret=${{ secrets.PRODUCTION_GITLAB_SECRET }} \
             django_secret=${{ secrets.PRODUCTION_DJANGO_SECRET }}" \
           deployment/deploy.yml
